// <auto-generated />
using System;
using ClimbBetter.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClimbBetter.Infrastructure.Migrations
{
    [DbContext(typeof(ClimbBetterDbContext))]
    [Migration("20260503112805_SeedLocationsAndClimbs")]
    partial class SeedLocationsAndClimbs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("training")
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Climb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DifficultyId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<int?>("LengthMeters")
                        .HasColumnType("integer");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("SuggestedMoveCount")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Climbs", "training");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1"),
                            DifficultyId = 2,
                            IsPublic = true,
                            LocationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Żółta 1",
                            SuggestedMoveCount = 7,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2"),
                            DifficultyId = 4,
                            IsPublic = true,
                            LocationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Żółta 2",
                            SuggestedMoveCount = 7,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa3"),
                            DifficultyId = 8,
                            IsPublic = true,
                            LocationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Żółta 3",
                            SuggestedMoveCount = 7,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb1"),
                            DifficultyId = 2,
                            IsPublic = true,
                            LengthMeters = 22,
                            LocationId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Ryski nad tablicą",
                            SuggestedMoveCount = 44,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb2"),
                            DifficultyId = 4,
                            IsPublic = true,
                            LengthMeters = 20,
                            LocationId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Filar Wallischa",
                            SuggestedMoveCount = 40,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb3"),
                            DifficultyId = 7,
                            IsPublic = true,
                            LengthMeters = 22,
                            LocationId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Zacięcie w Abazym",
                            SuggestedMoveCount = 44,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb4"),
                            DifficultyId = 7,
                            IsPublic = true,
                            LengthMeters = 22,
                            LocationId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Ryski Myszkowskiego",
                            SuggestedMoveCount = 44,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb5"),
                            DifficultyId = 8,
                            IsPublic = true,
                            LengthMeters = 22,
                            LocationId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Abazy Pasza",
                            SuggestedMoveCount = 44,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb6"),
                            DifficultyId = 8,
                            IsPublic = true,
                            LengthMeters = 22,
                            LocationId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Zacięcie w Abazym wprost",
                            SuggestedMoveCount = 44,
                            Type = 0
                        });
                });

            modelBuilder.Entity("Difficulty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Difficulties", "training");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "5c",
                            Points = 55
                        },
                        new
                        {
                            Id = 2,
                            Name = "6a",
                            Points = 60
                        },
                        new
                        {
                            Id = 3,
                            Name = "6a+",
                            Points = 65
                        },
                        new
                        {
                            Id = 4,
                            Name = "6b",
                            Points = 70
                        },
                        new
                        {
                            Id = 5,
                            Name = "6b+",
                            Points = 75
                        },
                        new
                        {
                            Id = 6,
                            Name = "6c",
                            Points = 80
                        },
                        new
                        {
                            Id = 7,
                            Name = "6c+",
                            Points = 85
                        },
                        new
                        {
                            Id = 8,
                            Name = "7a",
                            Points = 90
                        });
                });

            modelBuilder.Entity("Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Area")
                        .HasColumnType("text");

                    b.Property<string>("Continent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Sector")
                        .HasColumnType("text");

                    b.Property<string>("SubArea")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Locations", "training");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Area = "Kraków",
                            Continent = "Europe",
                            Country = "PL",
                            IsPublic = true,
                            Name = "Bronx",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Area = "Jura Krakowsko-Częstochowska",
                            Continent = "Europe",
                            Country = "PL",
                            IsPublic = true,
                            Name = "Filar Abazego",
                            Sector = "Dolina Bolechowicka",
                            SubArea = "Filar Abazego",
                            Type = 3
                        });
                });

            modelBuilder.Entity("Quality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Multiplier")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Qualities", "training");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "OS",
                            Multiplier = 1.20m,
                            Name = "Onsight"
                        },
                        new
                        {
                            Id = 2,
                            Code = "FL",
                            Multiplier = 1.10m,
                            Name = "Flash"
                        },
                        new
                        {
                            Id = 3,
                            Code = "RP",
                            Multiplier = 1.00m,
                            Name = "Redpoint"
                        },
                        new
                        {
                            Id = 4,
                            Code = "RRP",
                            Multiplier = 0.80m,
                            Name = "Repeat RP"
                        },
                        new
                        {
                            Id = 5,
                            Code = "ATT",
                            Multiplier = 1.00m,
                            Name = "Attempt"
                        },
                        new
                        {
                            Id = 6,
                            Code = "RTR",
                            Multiplier = 0.50m,
                            Name = "Repeat TR"
                        });
                });

            modelBuilder.Entity("TrainingEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CalculatedPoints")
                        .HasColumnType("integer");

                    b.Property<Guid>("ClimbId")
                        .HasColumnType("uuid");

                    b.Property<int>("CompletedMoveCount")
                        .HasColumnType("integer");

                    b.Property<int>("QualityId")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("TrainingEntries", "training");
                });

            modelBuilder.Entity("TrainingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TrainingSessions", "training");
                });
#pragma warning restore 612, 618
        }
    }
}
