// <auto-generated />
using System;
using ClimbBetter.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClimbBetter.Infrastructure.Migrations
{
    [DbContext(typeof(ClimbBetterDbContext))]
    [Migration("20260503102917_SeedDifficultiesAndQualities")]
    partial class SeedDifficultiesAndQualities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("training")
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Climb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DefaultMoveCount")
                        .HasColumnType("integer");

                    b.Property<int>("DifficultyId")
                        .HasColumnType("integer");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Climbs", "training");
                });

            modelBuilder.Entity("Difficulty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Difficulties", "training");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "5c",
                            Points = 55
                        },
                        new
                        {
                            Id = 2,
                            Name = "6a",
                            Points = 60
                        },
                        new
                        {
                            Id = 3,
                            Name = "6a+",
                            Points = 65
                        },
                        new
                        {
                            Id = 4,
                            Name = "6b",
                            Points = 70
                        },
                        new
                        {
                            Id = 5,
                            Name = "6b+",
                            Points = 75
                        },
                        new
                        {
                            Id = 6,
                            Name = "6c",
                            Points = 80
                        },
                        new
                        {
                            Id = 7,
                            Name = "6c+",
                            Points = 85
                        },
                        new
                        {
                            Id = 8,
                            Name = "7a",
                            Points = 90
                        });
                });

            modelBuilder.Entity("Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Locations", "training");
                });

            modelBuilder.Entity("Quality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Multiplier")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Qualities", "training");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "OS",
                            Multiplier = 1.20m,
                            Name = "Onsight"
                        },
                        new
                        {
                            Id = 2,
                            Code = "FL",
                            Multiplier = 1.10m,
                            Name = "Flash"
                        },
                        new
                        {
                            Id = 3,
                            Code = "RP",
                            Multiplier = 1.00m,
                            Name = "Redpoint"
                        },
                        new
                        {
                            Id = 4,
                            Code = "RRP",
                            Multiplier = 0.80m,
                            Name = "Repeat RP"
                        },
                        new
                        {
                            Id = 5,
                            Code = "ATT",
                            Multiplier = 1.00m,
                            Name = "Attempt"
                        },
                        new
                        {
                            Id = 6,
                            Code = "RTR",
                            Multiplier = 0.50m,
                            Name = "Repeat TR"
                        });
                });

            modelBuilder.Entity("TrainingEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CalculatedPoints")
                        .HasColumnType("integer");

                    b.Property<Guid>("ClimbId")
                        .HasColumnType("uuid");

                    b.Property<int>("CompletedMoveCount")
                        .HasColumnType("integer");

                    b.Property<int>("QualityId")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("TrainingEntries", "training");
                });

            modelBuilder.Entity("TrainingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TrainingSessions", "training");
                });
#pragma warning restore 612, 618
        }
    }
}
